services:
  browser-webapi:
    container_name: browser-webapi
    image: browser-webapi:dev
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - 3001:3001
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3001
      - USER_DATA_DIR=/app/chrome-profile
    volumes:
      - chrome-data:/app/chrome-profile

volumes:
  chrome-data: